### ISSUE TITLE
Allow TBTC and ETH usage for signing bonds in v2

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc#118]
Enabling TBTC as signing bond collateral can lower the overall collateral requirements of the supply peg.

Consider 10 BTC under custody. With a 6 month deposit term and 50 basis point fee, 9.95 TBTC are in circulation, and 15 BTCETH ("15 BTC worth of ETH") is bonded.

With optional TBTC signing bonds, 9 more BTC can be deposited and backed by 9 TBTC, meaning a total TBTC supply of 19 TBTC, only requiring 15 BTCETH in additional collateral. That's a 1.79X collateralization across the whole system, including Bitcoin and signing bonds- versus the 2.5X collateralization required naively by an ETH-only signing bond.

Fully playing out the example, more and more BTC can be deposited and backed by TBTC signing bonds. At 100 BTC, collateralization is only 1.15X- and as the BTC collateral grows further, the total collateral requirements approach 1.

At 100 BTC, however, only 9.5 TBTC is fully liquid- meaning that a 50 basis point return to signers and the use of 9.5 TBTC is the only incentive driving this loop. To see this behavior live, there needs to be additional incentive to sign and deposit. This incentive can be accomplished via #117. As long as signing bonds can be safely lent, the returns on those loans should incentivize signers to also act as large depositors.

- [x] Document the new behavior. A single signer can provide as much ETH as is required for overcollateralization, *or* 1X the TBTC they're signing for. No signers can mix collateral in a particular deposit, though across a deposit different signers can have chosen different types of collateral. For example, a 1 BTC deposit can be backed by a signing bond of 0.5 TBTC and 0.75 BTCETH.
- [x] Document how this impacts bonding choices and add any additional states
- [x] Document the lowered total collateral requirements by the whole system (demonstrated above)
- [ ] Implement the bond undercollateralization logic
- [ ] Implement the liquidation special case- the TBTC portion of a signing bond doesn't need to be liquidated, only burned.
- [ ] Implement the either / or option for bonded keeps.
