### ISSUE TITLE
Replacing the trusted price feed

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc#254]
This has been delayed to **v2**. MakerDAO's [Medianizer](https://developer.makerdao.com/feeds/) will be used for v1.

-----------

The system needs price information at two critical times

1) When a new `Deposit` is created, the system needs to know how much collateral should be required of signers. If the collateral is all `TBTC`, no feed is necessary.
2) The system needs to know when a `Deposit` becomes undercollateralized, as well as "how much" to decide whether to move to the "courtesy call" or "liquidation" state.

# Challenging deposit bonds

Let's ignore the first case for a moment, and focus on the second. Rather than treating price as a universal aspect of the system, we can focus on whether a particular deposit is undercollateralized. Anyone may challenge that a particular deposit is undercollateralized, and put some money down to prove it. If they're shown to be correct, they're paid a fee from liquidation.

To prove they're correct, the challenger puts down a bid for 1 BTC in ETH. We expect that the challenger will choose a favorable bid, rather than what they believe is the exact price, so if the bid is taken the challenger will make money. If the bid isn't taken within a timeout, we now have a ceiling on the BTC/ETH price.

# Generalizing to an orderbook

Generalizing this idea further, we can build a 1-sided cross-chain orderbook of bids for BTC. We can consider the "price ceiling" of BTC as the deepest bid in the orderbook that has stood unfulfilled for some timeout. Of course, we don't want that price to move very often.

An attacker who wants to move the oracle price will have to eat through the orderbook, suffering price slippage- but a well-funded attacker can always defeat a thin orderbook. To prevent this, arbitrageurs must be allowed to insert bids into the orderbook before an attacker can clear out the book, effectively frontrunning an attacker.

# New deposits

To decide the bond requirements for a new `Deposit`, all this scheme requires is a single bid that's been open long enough to be considered a legitimate price ceiling.

That time, however, might need to be as long as 24 hours- which leads to a poor deposit UX.

In the case that a price ceiling hasn't been established by the one-sided orderbook / challenge system, I suggest we fall back to Maker's existing BTC/USD and ETH/USD price feeds for new `Deposit` creation. If the feeds ever fail or aren't updated, we can fall back to the orderbook system.

The reliance on Maker feeds should be easy to turn off via user-activated governance. I'm working on better describing how that might look, but in the meantime a single privileged call to disable the Maker feed behavior by the contract owner should do it.

Thanks to @danrobinson @prestwich @nanexcool @afdudley and many others for the ideas behind this mechanism.

# Tasks

- [ ] Document how this price mechanic works, including distinguishing this hybrid market / trusted model vs purely trusted models and Schelling-based models
- [ ] Diagram the new state machine
- [ ] Specify the Solidity interfaces necessary to implement this scheme
- [ ] Implement the scheme
- [ ] Build a maintainer to challenge deposits based on prices from popular exchanges

Replaces #92
