### ISSUE TITLE
Optionally locked deposits spec

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc#293]
Removing the idea of "deposit ownership" [in favor of the deposit beneficiary NFT](https://github.com/keep-network/tbtc/issues/64) opened up a variety of desirable features, including signers being able to redeem deposits for which they have a bond (rather than N signers coordinating to "top up" their signing bonds in case of price shifts).

The downside, however, was removing the option for a class of depositors who want to maintain sole control of "their" deposit UTXO. A clear example is BTC depositors who want to use their BTC as collateral in systems like Maker- a fungible token doesn't add anything except borrower convenience, and actually abstracts economic information that would ideally be passed to CDPs.

After some thought, the two designs can be cleanly merged.

When a depositor opens a new deposit, before providing proof of a Bitcoin deposit, the depositor can be granted an NFT designating "ownership" of the deposit. This has a UX benefit- while depositors are waiting for confirmations on the Bitcoin chain, they can immediately transact with the NFT. For example

* Traders can trade 0- or 1-conf UTXOs rather than waiting. Every NFT could have probabilistic finality priced in. 
* Deposit proofs to mint TBTC can be optionally outsourced to a third party while maintaining decent UX.

These benefits don't threaten the TBTC / BTC supply peg, as no TBTC should be minted until a deposit is deemed "mature".

Once the BTC transaction is confirmed and heavy enough proof has been provided, a deposit is deemed mature. The depositor can continue to use the NFT, representing the sole right to redeem the deposit less signer fees, or they can mint TBTC. If they mint the fungible token, the NFT now acts as the "deposit beneficiary" token- a right to a future fee rebate if a deposit is redeemed.

At any time, a deposit beneficiary can "pay back" their minted TBTC, locking any deposit for which they have the corresponding NFT.

I believe this scheme is more flexible, and opens up a variety of UX improvements at both deposit and redemption- as well as an easier time for integrations with more specific needs.

- [x] Document the changes to token minting in prose (#294)
- [x] Document the changes to token redemption (#294)
- [x] Document the changes to liquidation of locked deposits, as well as deposit expiry; also clarify the risk of a locked deposit to signers -> *Locked deposits remain locked until liquidation; everything proceeds as before once we enter liquidation. Notably, deposits are STILL LOCKED during pre-liquidation.*
- [x] Document the economic changes, especially around fees and rebates
- [x] Capture all fees in the system (#301)
- [x] Ensure terminology around "redeemed" instead of e.g. "closed" for deposits is consistent (may merit its own issue)
- [x] Update the state diagram
- [x] Add minting state diagram
- [x] Investigate and describe zero-confirmation NFT minting (see [this comment](https://github.com/keep-network/tbtc/pull/294/files#r326957032) and [this comment](https://github.com/keep-network/tbtc/pull/294/files#r326957471)). -> *yes, on deposit opening*
- ~~Incentivize maintainer proof submission when depositors are absent (see [this comment](https://github.com/keep-network/tbtc/pull/294/files#r326958737)).~~ -> *TDTs allow us to tackle this post-mainnet*
- * ~~Decide on the need for deposit challenges for reorgs and describe if needed (see [this comment](https://github.com/keep-network/tbtc/pull/294/files#r326959275)). -> *we do need this, but leaving it on pause for now; there's support in the new summa relay, question is how critical is it for v1 vs documenting the possibility of an attack*~~ -> *dropping this for v1*
- [x] Decide on NFT handling if the underlying deposit is liquidated (see [this comment](https://github.com/keep-network/tbtc/pull/294/files#r326964554)). -> *If deposit is liquidated, NFT can float. If you receive an NFT, you should check its associated deposit for validity.*
- [x] Detail deposit qualifications (i.e., amount of work needed to mint TBTC from the vending machine) (see [this comment](https://github.com/keep-network/tbtc/pull/294/files#r326964201)).
- [x] More deeply describe redemption exclusivity (see [this comment](https://github.com/keep-network/tbtc/pull/294/files#r326966175)).
- ~~Specify the Solidity interfaces necessary to implement this scheme~~ -> tracked in #334 
- ~~Implement the scheme~~ -> tracked in #334

**Comment by Shadowfiend** [comment]
Okies, we're done here.
