### ISSUE TITLE
tECDSA 3-of-3 multi-signer implementation

### ISSUE THREAD

**Issue by Shadowfiend** [keep-network/tbtc#335]
Also involves:
- Investigating Binance implementation: https://github.com/binance-chain/tss-lib

High-level estimate: XL
Breakdown: @Shadowfiend @nkuba  

- [x] Read and understand Fast tECDSA paper - https://github.com/keep-network/keep-tecdsa/issues/91
- [x] Investigate Binance's tss-lib implementation - https://github.com/keep-network/keep-tecdsa/issues/92
- [x] Figure out structural dependencies between Binance/keep-core - https://github.com/keep-network/keep-tecdsa/issues/93
- [x] Implement protocol executor - https://github.com/keep-network/keep-tecdsa/issues/94
- [x] Key Generation stage execution - https://github.com/keep-network/keep-tecdsa/issues/95
- [x] Signing stage execution - https://github.com/keep-network/keep-tecdsa/issues/96
- [x] Integrate protocol executor with ECDSA keep client - https://github.com/keep-network/keep-tecdsa/issues/97
- [x] Upgrade libp2p - https://github.com/keep-network/keep-tecdsa/issues/98
- [x] Implement formation/DKG against libp2p - https://github.com/keep-network/keep-tecdsa/issues/99
- [x] Implement signing against libp2p - https://github.com/keep-network/keep-tecdsa/issues/100
- [x] Implement group teardown - https://github.com/keep-network/keep-tecdsa/issues/101
- [x] Implement signer choice for group - https://github.com/keep-network/keep-tecdsa/issues/102
- [x] Network messages transport - https://github.com/keep-network/keep-tecdsa/issues/103
- [x] Timeouts handling - https://github.com/keep-network/keep-tecdsa/issues/104
- [x] Implement smoke test - https://github.com/keep-network/keep-tecdsa/issues/105

May not block audit:
- Implement transaction submission to BTC: *4pt*
  Should we be doing this in the dApp only? tbtc-maintainer? Signing group?
- *Exploratory testing*: *8*
	Try to break as much as possible.

Audit total: 74pt
Total: 86pt

**Comment by Shadowfiend** [comment]
We done.
