### ISSUE TITLE
v1 "governance" checklist

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc#406]
- [x] Document intent to rely on "social upgrades" (a new set of contracts) rather than more complex mechanisms for code updates.
- [x] Document intent for any changes to only impact new deposits, not existing deposits
- [x] Govern the ETH to BTC overcollateralization factor for new deposits (#407)
- [x] Document [`emergencyPauseNewDeposits()`](https://github.com/keep-network/tbtc/issues/421) to pause new deposits
- [x] Document `beginLotSizesUpdate()` to adjust available lot sizes for new deposits
- [x] Document `beginSignerFeeDivisorUpdate()` to change the signing fee for new deposits
- [x] Document `beginCollateralizationThresholdsUpdate()` for new deposits
- [x] Document [`beginEthBtcPriceFeedAddition()`](https://github.com/keep-network/tbtc/blob/02b25f83d5f5a5a67549476a7bff418bb3bd933e/solidity/contracts/system/TBTCSystem.sol#L387) for fallback price feeds

**Comment by mhluongo** [comment]
Closed by #645
